My Portfolio Microverse Project Creating Desktop Version.
David-Kasilia/My-Portfolio-Microverse-Project pull request #4
Opened 2022-07-06 22:57 UTC by David-Kasilia

### **To Highlight**

- Created desktop-version-feature-branch
- Created media.css for the media query code to work on the responsiveness on the desktop version.
- Updated index.html by adding necessary forms and headings that will appear on the desktop version only
- Updated style.css to meet the responsiveness of the website

2022-07-07 15:24 UTC, codecaiine requested changes
Hi @David-Kasilia , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
-  Clean code :heavy_check_mark: 

## Required Changes ♻️

- [x]  Kindly work on your design changes on transition in some widths the alignment and layout are wrong kindly make it a bit smoother.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 15:24 UTC, codecaiine commented on index.html
> +      <hr class="line-bottom"/>
- [ ] Please change this line to grey line as part of Figma design :smile:

2022-07-08 12:58 UTC, codecaiine commented on index.html
> -      <div class="contacts">
hi @David-Kasilia, thank you for asking. You need just one form for both mobile and desktop versions. Now, this milestone aims to make every element of your website adapt to different devices (Mobile and Desktop). You don't need to duplicate the elements. Hope that helps you :smile:

2022-07-08 14:37 UTC, 1GORDON requested changes
##
## Hi @David-Kasilia ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Professional Readme ✔️
- Professional Pull Request ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] You may please try to resolve the issues that could have been created by the new changes you introduced.

_Check the comments under the review._

- [ ] [Optional] You may please make the gray color throughout your design a darker gray so as to match the colors in the Figma design. Please checkout the Figma template for guidance

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 15:05 UTC, David-Kasilia commented on index.html
> +      </div>
@1GORDON Hello, Thank you for your review, Why is is that on my side it all seems okay. Any suggestions why
![Screenshot 2022-07-08 at 18-03-42 My Portfolio Second Milestone](https://user-images.githubusercontent.com/83514256/178019263-afeb3796-a13d-4966-b924-a0123888ca85.png)

2022-07-08 15:07 UTC, David-Kasilia commented on index.html
>      <section id="recent-work">
Hello, @1GORDON . Thank you for your review.May you help me see to it why is appearing okay on my screen
![Screenshot 2022-07-08 at 18-06-57 My Portfolio Second Milestone](https://user-images.githubusercontent.com/83514256/178019731-7fd69ed3-37f4-4b46-a803-bf0baa93a49e.png)
?

2022-07-08 15:08 UTC, David-Kasilia commented on index.html
>      <section id="recent-work">
@1GORDON , Hello. May you help me in understanding this review, is this the overall summary of the review:
You may please try to resolve the issues that could have been created by the new changes you introduced.

2022-07-08 20:13 UTC, Ugboaja-Uchechi approved these changes
Hi @David-Kasilia , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 20:16 UTC, merged